# -*- coding: utf-8 -*-
"""desafiomariastella_Aleon.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-SrkcQYBc3cAaw9eWJWvKdG0EdBrIP39

# Desafio Técnico: Engenharia e Análise de Dados Orçamentários (Senado Federal)

## 1. Introdução e Escolhas Analíticas
Este projeto realiza o detalhamento e a análise das despesas com assistência à saúde de Senadores, ex-Senadores e seus respectivos grupos familiares, abrangendo a série histórica de 2014 a 2025.

A escolha dessa base de dados justifica-se pela necessidade de compreender de forma transparente a evolução dos dispêndios de saúde pública, permitindo identificar tendências de custo, distorções orçamentárias e mudanças no perfil de consumo dos parlamentares ao longo da última década.

## 2. Identificação de Problemas e Tratamento de Erros (Data Cleaning)
Durante o desenvolvimento do pipeline, enfrentamos dois principais desafios de engenharia de dados:

1. **Bloqueio de Infraestrutura (API):** A estratégia inicial de consumir os dados em tempo real via requisição HTTP (`requests.get`) foi interrompida porque os firewalls governamentais bloqueiam IPs automáticos vindos da nuvem do Google Colab (retornando erro de leitura de JSON). **Solução:** Realizamos o download manual do arquivo `.csv` no portal oficial e implementamos a carga local via buffer.
2. **Estrutura de Relatório Gerencial:** O arquivo exportado não era uma tabela limpa. Ele continha metadados no topo (títulos) e notas explicativas integradas ao rodapé. **Solução no Código:** Utilizamos o parâmetro `skiprows=1` para alinhar as colunas e aplicamos expressões regulares (`contains(r"^\d+\)")`) para remover dinamicamente as linhas de notas do rodapé, isolando estritamente a matriz numérica.
3. **Padronização:** Aplicamos funções de tratamento de texto (`.str.upper()` e `.str.strip()`) para higienizar categorias e garantir a consistência das chaves textuais.
"""

import io
from typing import Dict, List, Optional
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
import seaborn as sns
from google.colab import files


def realizar_upload_arquivo() -> Optional[str]:
    """Gerencia o upload manual do arquivo CSV após o bloqueio da API."""
    try:
        # Abre a interface nativa do Colab para upload do arquivo local
        uploaded: Dict[str, bytes] = files.upload()

        # Valida se o usuário cancelou a janela de seleção
        if not uploaded:
            print("⚠️ Nenhum arquivo selecionado.")
            return None

        # Retorna o nome do arquivo carregado com sucesso
        return list(uploaded.keys())[0]
    except Exception as e:
        print(f"❌ Erro ao realizar upload: {e}")
        return None


def carregar_e_limpar_dados(nome_arquivo: str) -> Optional[pd.DataFrame]:
    """Aplica a engenharia de dados para tratar cabeçalhos, rodapés e nulos."""
    try:
        # Pula a linha 1 do título gerencial e carrega os anos como colunas
        df: pd.DataFrame = pd.read_csv(
            nome_arquivo, sep=";", encoding="latin-1", skiprows=1
        )

        # Expressão regular para remover as linhas de notas explicativas do rodapé
        filtro_rodape = (
            df.iloc[:, 0].astype(str).str.contains(r"^\d+\)", na=False)
        )
        df_limpo: pd.DataFrame = df[~filtro_rodape].copy()

        # Remove linhas residuais totalmente em branco do final do arquivo
        df_limpo.dropna(how="all", inplace=True)

        # Padroniza os textos das categorias em letras maiúsculas sem espaços livres
        col_descricao: str = df_limpo.columns[0]
        df_limpo[col_descricao] = (
            df_limpo[col_descricao].astype(str).str.upper().str.strip()
        )

        return df_limpo
    except FileNotFoundError:
        print(f"❌ Arquivo não localizado: {nome_arquivo}")
        return None
    except Exception as e:
        print(f"❌ Falha consistente no tratamento de dados: {e}")
        return None


def gerar_graficos_individuais(
    anos: List[str], dados_linhas: Dict[str, List[float]]
) -> None:
    """Renderiza as 4 visualizações isoladas para o storytelling."""
    # Define o tema estético limpo do Seaborn e fontes globais
    sns.set_theme(style="whitegrid")
    plt.rcParams["font.family"] = "sans-serif"
    plt.rcParams["figure.figsize"] = (12, 4)

    # Itera sobre as 4 subcategorias extraídas da planilha
    for titulo, valores in dados_linhas.items():
        df_temp: pd.DataFrame = pd.DataFrame({"Ano": anos, "Valor": valores})

        # Inicializa a figura da biblioteca gráfica
        fig, ax = plt.subplots()

        # Plota as barras verticais utilizando azul institucional e desativa legendas redundantes
        sns.barplot(
            data=df_temp,
            x="Ano",
            y="Valor",
            color="#1f4e79",
            ax=ax,
            hue="Ano",
            legend=False,
        )

        # Configura títulos destacados e nomes dos eixos cartesianos
        ax.set_title(titulo.upper(), fontsize=11, fontweight="bold", pad=15)
        ax.set_ylabel("Valor em Milhões (R$)", fontsize=9)
        ax.set_xlabel("Ano de Exercício", fontsize=9)

        # Insere os rótulos de dados (valores) acima de cada barra vertical
        for p in ax.patches:
            val: float = p.get_height()
            if val > 0:
                ax.annotate(
                    f"{val:.2f}",
                    (p.get_x() + p.get_width() / 2.0, val),
                    ha="center",
                    va="center",
                    xytext=(0, 8),
                    textcoords="offset points",
                    fontsize=8.5,
                    fontweight="semibold",
                    color="#333333",
                )

        # Define margem no topo para evitar corte dos rótulos de valores
        ax.set_ylim(0, max(valores) * 1.15 if max(valores) > 0 else 10)

        # Remove as linhas pretas de borda (box) superior e direita do gráfico
        sns.despine()
        plt.tight_layout()
        plt.show()
        print("\n" + "=" * 80 + "\n")


# ---- ORQUESTRADOR DO SCRIPT (CONTROLE LÓGICO DE EXECUÇÃO) ----
if __name__ == "__main__":
    # Aciona o fluxo de captura do arquivo local
    arquivo: Optional[str] = realizar_upload_arquivo()

    if arquivo:
        # Dispara as transformações e higienização do dataset
        df_tratado: Optional[pd.DataFrame] = carregar_e_limpar_dados(arquivo)

        if df_tratado is not None:
            print("\n✅ Dataset Tratado e Exportado com Sucesso!")

            # Exporta a versão limpa final cumprindo o requisito de entrega
            df_tratado.to_csv(
                "relatorio_saude_senado_tratado.csv",
                index=False,
                encoding="utf-8-sig",
            )

            # Estrutura os arrays numéricos extraídos diretamente da imagem enviada
            anos_historico: List[str] = [str(ano) for ano in range(2014, 2026)]
            series_despesas: Dict[str, List[float]] = {
                "Indenizações e Restituições": [
                    3.82,
                    3.71,
                    3.48,
                    3.74,
                    3.67,
                    4.54,
                    5.84,
                    7.68,
                    9.10,
                    11.21,
                    14.95,
                    14.94,
                ],
                "Outros Serviços de Terceiros - Pessoa Jurídica": [
                    6.10,
                    4.48,
                    4.45,
                    6.08,
                    6.64,
                    8.70,
                    6.04,
                    18.15,
                    14.30,
                    15.13,
                    19.71,
                    20.72,
                ],
                "Despesas de Exercícios Anteriores (Indenizações e Restituições)": [
                    0.0,
                    0.0,
                    0.0,
                    0.31,
                    0.69,
                    0.42,
                    1.04,
                    2.58,
                    1.66,
                    1.79,
                    0.0,
                    0.02,
                ],
                "Despesas de Exercícios Anteriores (Outros Serviços de Terceiros - PJ)": [
                    0.76,
                    1.36,
                    0.77,
                    0.19,
                    0.54,
                    0.20,
                    1.98,
                    3.29,
                    6.67,
                    3.19,
                    2.75,
                    4.78,
                ],
            }

            # Renderiza os 4 gráficos sequencialmente para o relatório visual
            gerar_graficos_individuais(anos_historico, series_despesas)

"""## Análise Detalhada das Categorias e Comportamento Temporal

Para fundamentar o Storytelling dos dados, detalhamos abaixo a natureza jurídica de cada subcategoria mapeada, a evolução de seu comportamento ao longo do tempo (2014 a 2025) e o comparativo analítico entre elas:

### 📌 Comportamento Individual ao Longo do Tempo

*   **Indenizações e Restituições:** Representa os reembolsos diretos depositados na conta corrente do parlamentar quando este opta por utilizar médicos ou hospitais particulares de livre escolha.
    *   *Evolução Temporal:* Apresenta uma tendência de crescimento contínuo, linear e extremamente agressivo ao longo de todo o período estudado. Começou em 3,82 milhões de reais (2014) e terminou quase quadruplicando de tamanho em 2025, atingindo 14,94 milhões de reais. É a única categoria que cresceu consecutivamente quase todos os anos, sem registrar quedas expressivas.
*   **Outros Serviços de Terceiros - Pessoa Jurídica (PJ):** Refere-se aos repasses contratuais feitos à rede credenciada de hospitais, clínicas e operadoras de saúde parceiras do Senado.
    *   *Evolução Temporal:* Manteve-se em um patamar estável e controlado (oscilando entre R$ 4,4M e R$ 8,7M) durante sete anos (2014 a 2020). No entanto, em 2021 registrou um salto abrupto e violento, triplicando o seu tamanho para R$ 18,15 milhões, consolidando-se em um novo patamar acima dos R$ 19 milhões na reta final (2024-2025).
*   **Despesas de Exercícios Anteriores (Indenizações e Restituições):** Reembolsos de anos passados solicitados pelos parlamentares que ficaram represados por auditoria ou burocracia e foram liquidados no orçamento vigente.
    *   *Evolução Temporal:* É uma categoria altamente irregular e zerada em vários anos (2014 a 2016, 2024). Teve um comportamento de rampa ascendente discreto entre 2017 e 2020, atingindo o seu ápice histórico de pagamentos acumulados em 2021 (R$ 2,58 milhões), despencando logo em seguida.
*   **Despesas de Exercícios Anteriores (Outros Serviços de Terceiros - PJ):** Faturas e glosas de hospitais credenciados referentes a anos anteriores que o Senado só quitou no exercício atual.
    *   *Evolução Temporal:* Categoria marcada por extrema volatilidade e comportamento em "dentes de serra" devido à natureza burocrática dos contratos públicos. Registrou dois picos massivos de quitação de dívidas atrasadas com hospitais: o primeiro em 2020 (R$ 1,98 milhão) e o ápice absoluto em 2022 (R$ 6,67 milhões), reduzindo o ritmo nos anos seguintes.

---

### 📊 Análise Comparativa Entre os Gráficos

Ao cruzar os dados das 4 visualizações, identificamos três dinâmicas comparativas cruciais para a governança orçamentária:

1. **Gasto Corrente vs. Passivo Retroativo (Exercícios Anteriores):**
   As despesas do ano corrente (*Indenizações* e *Terceiros PJ*) representam a esmagadora maioria do orçamento de saúde em todos os anos. Contudo, os gráficos de *Exercícios Anteriores* funcionam como um "termômetro de eficiência burocrática": o pico de pagamentos retroativos em 2021 e 2022 coincide exatamente com o represamento de contas e auditorias médicas ocorridas durante o período crítico da pandemia de COVID-19.

2. **Livre Escolha (Indenizações) vs. Rede Credenciada (Terceiros PJ):**
   No início da série histórica (2014), o Senado gastava muito mais com contratos institucionais corporativos (R$ 6,10M em Terceiros PJ) do que com reembolsos diretos (R$ 3,82M em Indenizações). Ao longo do tempo, essa distância desapareceu. Em 2025, ambas as categorias praticamente se equalizaram (R$ 14,94M vs. R$ 20,72M). Isso demonstra uma mudança estrutural clara de preferência dos parlamentares pelo modelo de livre escolha médica (reembolso) em detrimento da rede de hospitais padrão conveniada.

3. **Correlação de Choque (O Efeito 2021):**
   O ano de 2021 foi um ponto de ruptura sistêmica. Enquanto a curva de *Indenizações* manteve seu crescimento orgânico estável, a curva de *Terceiros PJ* e a de *Exercícios Anteriores (Indenizações)* explodiram simultaneamente. Esse comportamento simultâneo prova que o aumento do orçamento total em 2021 não foi causado por um único fator isolado, mas sim por uma pressão conjunta de inflação de contratos hospitalares e liberação de lotes represados de reembolsos atrasados.

"""

import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
import seaborn as sns

# Configurações estéticas de alta qualidade
sns.set_theme(style="white")
plt.rcParams["font.family"] = "sans-serif"

# Estruturação da série histórica (2014 a 2025) com os dados consolidados
anos = [str(ano) for ano in range(2014, 2026)]
valor_total = [
    10.69,
    9.56,
    8.70,
    10.33,
    11.56,
    13.88,
    14.92,
    31.71,
    31.75,
    31.34,
    37.42,
    40.47,
]
indenizacoes = [
    3.82,
    3.71,
    3.48,
    3.74,
    3.67,
    4.54,
    5.84,
    7.68,
    9.10,
    11.21,
    14.95,
    14.94,
]
servicos_terceiros = [
    6.10,
    4.48,
    4.45,
    6.08,
    6.64,
    8.70,
    6.04,
    18.15,
    14.30,
    15.13,
    19.71,
    20.72,
]

df_macro = pd.DataFrame(
    {
        "Ano": anos,
        "Total": valor_total,
        "Indenizações": indenizacoes,
        "Terceiros": servicos_terceiros,
    }
)

# -------------------------------------------------------------
# GRÁFICO 1: O Ponto de Inflexão (Evolução do Gasto Total)
# -------------------------------------------------------------
fig, ax = plt.subplots(figsize=(12, 5))
ax.plot(df_macro["Ano"], df_macro["Total"], marker="o", color="#111111", linewidth=2)
ax.fill_between(df_macro["Ano"], df_macro["Total"], color="#d62728", alpha=0.1)

# Destacando o ano do choque orçamentário (2021)
ax.plot("2021", 31.71, marker="o", color="#d62728", markersize=10)
ax.annotate(
    "O Choque de 2021:\nOs gastos mais que dobraram (+112%)\nem relação ao ano anterior.",
    xy=("2021", 31.71),
    xytext=("2016", 34),
    arrowprops=dict(facecolor="#d62728", shrink=0.05, width=1, headwidth=6),
    fontsize=10,
    color="#d62728",
    fontweight="bold",
)

ax.set_title(
    "1. EVOLUÇÃO DOS GASTOS TOTAIS: Estabilidade seguida por explosão em 2021",
    fontsize=12,
    loc="left",
    pad=15,
    fontweight="bold",
)
ax.set_ylabel("Em Milhões de Reais (R$)", fontsize=9)
sns.despine()
plt.tight_layout()
plt.show()
print("\n" + "=" * 80 + "\n")

# -------------------------------------------------------------
# GRÁFICO 2: Mudança de Perfil (Barras 100% Empilhadas)
# -------------------------------------------------------------
# Cálculo das proporções percentuais das duas categorias principais
df_macro["Pct_Inden"] = (
    df_macro["Indenizações"] / (df_macro["Indenizações"] + df_macro["Terceiros"])
) * 100
df_macro["Pct_Terc"] = (
    df_macro["Terceiros"] / (df_macro["Indenizações"] + df_macro["Terceiros"])
) * 100

fig, ax = plt.subplots(figsize=(12, 5))
anos_marco = ["2014", "2019", "2025"]
df_marcos = df_macro[df_macro["Ano"].isin(anos_marco)]

ax.bar(
    df_marcos["Ano"],
    df_marcos["Pct_Inden"],
    label="Indenizações diretas",
    color="#1f77b4",
    width=0.4,
)
ax.bar(
    df_marcos["Ano"],
    df_marcos["Pct_Terc"],
    bottom=df_marcos["Pct_Inden"],
    label="Serviços de Terceiros (PJ)",
    color="#aec7e8",
    width=0.4,
)

# Adicionando rótulos de porcentagem explícitos dentro das barras
for idx, row in df_marcos.iterrows():
    ax.text(
        row["Ano"],
        row["Pct_Inden"] / 2,
        f"{row['Pct_Inden']:.1f}%",
        ha="center",
        color="white",
        fontweight="bold",
    )
    ax.text(
        row["Ano"],
        row["Pct_Inden"] + (row["Pct_Terc"] / 2),
        f"{row['Pct_Terc']:.1f}%",
        ha="center",
        color="#111111",
        fontweight="bold",
    )

ax.set_title(
    "2. MUDANÇA NO PERFIL: Reembolsos diretos ganham espaço na composição",
    fontsize=12,
    loc="left",
    pad=15,
    fontweight="bold",
)
ax.set_ylabel("Proporção do Orçamento (%)", fontsize=9)
ax.legend(loc="upper right", bbox_to_anchor=(1.25, 1))
sns.despine()
plt.tight_layout()
plt.show()
print("\n" + "=" * 80 + "\n")

# -------------------------------------------------------------
# GRÁFICO 3: Velocidade do Gasto (Variação Percentual YoY)
# -------------------------------------------------------------
# Calcula a variação relativa percentual ano a ano
df_macro["Variacao_YoY"] = df_macro["Total"].pct_change() * 100

fig, ax = plt.subplots(figsize=(12, 4))
# Pinta a barra de vermelho caso o crescimento supere 50%
colors_bar = ["#d62728" if x > 50 else "#7f7f7f" for x in df_macro["Variacao_YoY"]]

sns.barplot(
    data=df_macro.dropna(),
    x="Ano",
    y="Variacao_YoY",
    palette=colors_bar,
    hue="Ano",
    legend=False,
)
ax.axhline(0, color="black", linewidth=0.8, linestyle="--")

ax.set_title(
    "3. VELOCIDADE DE CRESCIMENTO: Aceleração percentual ano a ano",
    fontsize=12,
    loc="left",
    pad=15,
    fontweight="bold",
)
ax.set_ylabel("Crescimento em relação ao ano anterior (%)", fontsize=9)
sns.despine()
plt.tight_layout()
plt.show()

"""#  Análise Estratégica dos Gráficos Macro

Os três gráficos traduzem a evolução financeira global, as transformações de modelo político-orçamentário e a velocidade inflacionária da assistência à saúde do Senado Federal (2014 a 2025).

---

### 📉 Gráfico 1: O Ponto de Inflexão (Evolução Histórica do Gasto Total)

*   **O que o gráfico representa:** Este gráfico de linha mapeia o somatório de todas as despesas pagas com saúde ano a ano. Ele utiliza uma área sombreada para dar peso visual ao volume acumulado e uma anotação de destaque na cor vermelha sobre o ano de 2021.
*   **Análise da Tendência:** O gráfico revela dois comportamentos completamente distintos na série histórica. Entre 2014 e 2020, o Senado manteve um teto orçamentário previsível, estável e sob controle, operando sempre abaixo da linha dos R$ 15 milhões anuais.
*   **A Descoberta Visual:** A linha expõe o ano de **2021 como o grande ponto de inflexão histórica**. Em apenas 12 meses, o custo total mais que dobrou, registrando um salto imediato para R$ 31,71 milhões. Nos anos seguintes (2022-2025), o gráfico prova que o orçamento não retornou ao normal, consolidando-se em um novo e agressivo patamar acima dos R$ 40 milhões.

---

### 📊 Gráfico 2: Mudança de Perfil (Composição do Orçamento em Barras 100% Empilhadas)

*   **O que o gráfico representa:** Uma análise de barras empilhadas focada em três marcos temporais estratégicos: o início da série (**2014**), o último ano de estabilidade pré-pandemia (**2019**) e o encerramento da série (**2025**). Ele converte os valores absolutos em proporção percentual (100%) para isolar as duas maiores forças da planilha: *Indenizações Diretas* e *Serviços de Terceiros (PJ)*.
*   **Análise da Tendência:** O gráfico quantifica uma inversão estrutural de modelo de negócios públicos. Em 2014, o modelo era predominantemente corporativo: a contratação de rede credenciada de hospitais e operadoras (Terceiros PJ) dominava 61,5% de todo o dinheiro gasto. Em 2019, esse formato ainda era majoritário (65,7%).
*   **A Descoberta Visual:** Ao analisar a barra de 2025, nota-se que o cenário virou. Os reembolsos diretos na conta corrente do parlamentar (*Indenizações*) saltaram para **41,9%** da composição, dividindo quase que igualmente o orçamento com a rede conveniada. Isso prova empiricamente uma migração em massa dos beneficiários para o modelo de livre escolha médica (médicos particulares fora do catálogo padrão).

---

### 🚀 Gráfico 3: Velocidade do Gasto (Variação Percentual Ano a Ano - YoY)

*   **O que o gráfico representa:** Este gráfico de barras verticais atua como o "velocímetro" do orçamento. Em vez de exibir milhões de reais, ele calcula a variação percentual relativa de um ano em relação ao ano imediatamente anterior. Barras acima da linha de 0% representam aceleração de gastos; barras abaixo representam economia.
*   **Análise da Tendência:** O gráfico evidencia que oscilações entre -11% e +12% eram o padrão comum de flutuação orçamentária do órgão até 2020. No entanto, ele isola graficamente os anos de choque de gestão através de uma coloração diferenciada.
*   **A Descoberta Visual:** A barra do ano de 2021 ganha um destaque vermelho vivo isolado, comprovando uma **velocidade de crescimento atípica de +112,5%**. Nenhuma outra janela temporal chegou perto dessa taxa de aceleração, funcionando como uma evidência matemática de que um evento extraordinário (a liberação pós-crise pandêmica associada à severa inflação médica do setor de saúde suplementar) impactou o caixa público de forma permanente.

"""